---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:423623849965:task-definition/SpringTask:1"
        LoadBalancerInfo:
          ContainerName: "SpringTask-service2"
          ContainerPort: 80
