version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing newer Maven...
      - wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
      - tar xzvf apache-maven-3.8.8-bin.tar.gz
      - export M2_HOME=$PWD/apache-maven-3.8.8
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -version
      - echo Installing dependencies...
      - yum install -y jq
      - echo Logging in to Amazon ECR...
      - export ACCOUNT_ID=423623849965
      - export REGION=us-east-1
      - export REPO_NAME=spring
      - export IMAGE_TAG=latest
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Building the JAR file...
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - docker tag $REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"springtask-service1","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s"}]' $ACCOUNT_ID $REGION $REPO_NAME $IMAGE_TAG > imagedefinitions.json
      - echo Writing appspec.yml...

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
